### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by naved001** [nerc-project/coldfront-plugin-cloud#102]
https://github.com/nerc-project/coldfront-plugin-cloud/actions/runs/4948674599/jobs/8849743668#step:5:82

This is coming from the radosgw setup file
```
./ci/radosgw.sh: line 65: cephadm: command not found
+ rgw_setup
+ cephadm shell ceph orch apply rgw test --placement=1
./ci/radosgw.sh: line 69: cephadm: command not found
Error: Process completed with exit code 127.
```

**Comment by knikolla** [comment]
Further up on the logs it seems to fail to get the package

Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 cephadm amd64 17.2.5-0ubuntu0.22.04.2
[24](https://github.com/nerc-project/coldfront-plugin-cloud/actions/runs/4948674599/jobs/8849743668#step:5:25)
  404  Not Found [IP: 40.81.13.82 80]
