### ISSUE TITLE
Set default limitrange for OpenShift pods to have the same ratios as used for SU definitions

### ISSUE THREAD

**Issue by naved001** [nerc-project/coldfront-plugin-cloud#108]
right now it's 1CPU to 0.5 Gig of memory. We probably want it something like 0.5 CPU to 2Gig of memory. We could also find out the most common size and base the default on that with the correct ratio.

Edit: 
Q1. What should the default pod size be? 0.5 CPU and 2 GiB RAM, or 0.25 CPU and 1 GiB RAM? It's best to keep it at 1:4 ratio so it aligns with our SU definitions. I will use these same to enforce as the minimum pod sizes here: https://github.com/nerc-project/operations/issues/602

Q2. After this change is made, how will the current limitranges be updated? (Maybe that is outside the scope of this issue, but it we need to make that it's captured somewhere).

**Comment by joachimweyl** [comment]
@naved001 is this something you feel you could do next sprint with @knikolla as backup if you have questions?

**Comment by joachimweyl** [comment]
@naved001 please add questions to this issue so we can finalize and then create the PR.

**Comment by naved001** [comment]
@jtriley I have proposed [this PR](https://github.com/CCI-MOC/openshift-acct-mgt/pull/102) to address this issue and https://github.com/nerc-project/operations/issues/602

**Comment by naved001** [comment]
closed by https://github.com/CCI-MOC/openshift-acct-mgt/pull/102
