### ISSUE TITLE
[OpenShift] add the ability to apply labels to new projects/namespaces

### ISSUE THREAD

**Issue by jtriley** [nerc-project/coldfront-plugin-cloud#113]
For the RHODS project we'll need to be able to label a given OpenShift allocation in order for it to show up as an available namespace for launching ODS workbenches.

**Comment by joachimweyl** [comment]
@jtriley what is the status of this issue?

**Comment by joachimweyl** [comment]
@jtriley I believe this is resolved is that correct?

**Comment by jtriley** [comment]
Not yet - still need to add the support to both this repo and https://github.com/CCI-MOC/openshift-acct-mgt

**Comment by jtriley** [comment]
First part is ready for review: https://github.com/CCI-MOC/openshift-acct-mgt/pull/98

**Comment by jtriley** [comment]
and the second part is also ready for review: https://github.com/nerc-project/coldfront-plugin-cloud/pull/115
