### ISSUE TITLE
Investigate merging `openshift-acct-mgt` into plugin

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#114]
We initially designed the integration with OpenShift to go through a small microservice, [openshift-acct-mgt](https://github.com/cci-moc/openshift-acct-mgt), which would provide the initial implementation of an API we were hoping to standardize across the various cloud services we would offer. The idea was to have a driverless mechanism for integrating more service offerings through a standard API to reduce the necessary code changes in ColdFront to support more services.

Therefore, the current implementation of OpenShift integration makes API calls to this microservice, rather than to OpenShift's API itself.

It's been a few years now and the decoupling that we hoped to achieve didn't realize. 

In fact this split has made it harder and more time consuming to add new features to our integration as
- changes need to be made in both places, sometimes resulting in a leaky abstraction.
- There's a strong coupling between both codebases, and changes need to be deployed in sync, making it harder to deploy.

ColdFront needs to know the implementation details of each service to expose their unique features, so the communication between ColdFront and the Cloud Service proved to not be the right place to introduce an abstraction. ColdFront itself should be the abstraction.

I believe we should strongly consider folding that codebase into the plugin and calling the OpenShift API directly. This would result in a more agile implementation that is easier to deploy and consume.

The API that we should standardize on, is the one that [ColdFront is exposing and that we're already developing](https://github.com/nerc-project/coldfront-plugin-api), as that can be exposed to our users and by implementing a standard like SCIM, may potentially allow automated provisioning scenarios for our users. There's a much larger potential for gathering a community around it.

**Comment by joachimweyl** [comment]
@knikolla is this expected to be worked on this sprint or shall we push this out to the next sprint?

**Comment by knikolla** [comment]
Work to merge has been started so I'm closing this out. Will create new issues for the various steps of merge.
