### ISSUE TITLE
Adding `Institution - Specific Code` - an institution-provided code (ie Customer Code) to help them internally track Projects/PIs as a new Allocation Quota Attribute

### ISSUE THREAD

**Issue by Milstein** [nerc-project/coldfront-plugin-cloud#129]
## Motivation
We need to add a new field to ColdFront that users can add when they create a new project. They will also need to be able to modify it if their `Institution - Specific Code` changes. This code will help Institutions track internal PI or project codes. This will be used for billing purpose and part of the exporting monthly csv file.

### Requirements
- `Institution - Specific Code`  quota attribute is available to both OpenStack and OpenShift resource type.
- the code can contain numbers and letters and "-". Max length 50 char.
- Available by default.
- PI/ Manager(s) can modify its value
- Running the `validate_allocations` command must be run to automatically populate the attribute in all ColdFront's allocations.

## Completion Criteria
able to add Institution - Specific Code to projects in Cold Front.

## Description
- [ ] Create Institution - Specific Code in Coldfront
   - max length 50 char
   - numbers and letters and "-"
- [ ] test that we can add Institution - Specific Code to project
- [ ] test that we can change Institution - Specific Code after a project is created
- [ ] test that we can add NA in the field

## Invoice Script
- OpenShift script will be updated [here](https://github.com/CCI-MOC/openshift-usage-scripts/issues/28)
- OpenStack script will be updated [here](https://github.com/CCI-MOC/openstack-billing-from-db/issues/28)

## Completion dates
Desired - 2023-12-22
Required - 2024-12-19

**Comment by joachimweyl** [comment]
@jtriley please let us know if you need any additional information for this issue.
