### ISSUE TITLE
When the Allocation Swift Storage Quota Attribute i.e. "OpenStack Swift Quota in Gigabytes" set to 0 provides unlimited quota to the user.

### ISSUE THREAD

**Issue by Milstein** [nerc-project/coldfront-plugin-cloud#147]
- "**OpenStack Swift Quota in Gigabytes**" value is set to 0.
- RGW interprets 0 as meaning unlimited quota as pointed [here](https://github.com/ceph/ceph/blob/1c349451176cc5b4ebfb24b22eaaa754e05cff6c/src/rgw/rgw_op.cc#L3311-L3313).
- It successfully removes the `properties | Quota-Bytes` while checking using `openstack object store account show` command.
- We can't set the `Quota-Bytes` property to `0` or `Empty` so we need set it to `1` byte that will the minimal we can set to prevent any future cost to the user.

**Comment by knikolla** [comment]
@Milstein tested that setting the quota to 1 byte prevents people from upload files larger than 1 byte.

Until the code is in place and deployed setting the ColdFront quota to zero and then manually setting the RGW quota to 1 byte using the command line will prevent people from being billed for storage.

**Comment by joachimweyl** [comment]
@Milstein is @knikolla's suggestion enough to close this and unblock https://github.com/nerc-project/operations/issues/304 ?

**Comment by joachimweyl** [comment]
@Milstein checking if this issue is ready to close.
