### ISSUE TITLE
Migrating discontinued Keycloak container used by Devstack testing 

### ISSUE THREAD

**Issue by QuanMPhm** [nerc-project/coldfront-plugin-cloud#149]
The current Keycloak container by jboss that we are using to test the Openstack plugin is now discontinued, preventing functional testing of our Openstak integration to fail. The Devstack functional tests are also using an [out-of-date OpenID plugin](https://github.com/nerc-project/coldfront-plugin-cloud/blob/6228541b18ca776124d5096ff8ecca2109df1634/ci/devstack.sh#L16). 

From @knikolla's advice, the solution is to migrate to using Keycloak's upstream OpenID plugin, and to use a new Keycloak container.

**Comment by knikolla** [comment]
The OIDC plugin as been merged into upstream Keystone so please look into switching from my plugin to that (it's still mostly based on my code)

https://github.com/openstack/keystone/blob/b08e5b5f63f50775a4cf1f2928bacf6995e56322/devstack/plugin.sh#L20
