### ISSUE TITLE
Implement support for excluding time intervals during an invoicing period

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#166]
Example, do not charge for storage during the MGHPCC shutdown.

**Comment by QuanMPhm** [comment]
@knikolla To clarify, you want to add an option in `calculate_storage_gb_hours.py` that allows us to exclude any arbitrary time interval from billing, such that storage usage within those time periods will not be billed? If that's the case, what is the granularity of the time interval? Days? Hours?

**Comment by knikolla** [comment]
> @knikolla To clarify, you want to add an option in `calculate_storage_gb_hours.py` that allows us to exclude any arbitrary time interval from billing, such that storage usage within those time periods will not be billed? If that's the case, what is the granularity of the time interval? Days? Hours?

@QuanMPhm Correct. The granularity is days.

**Comment by QuanMPhm** [comment]
@knikolla I was reviewing the storage billing code, and was confused by this [line](https://github.com/nerc-project/coldfront-plugin-cloud/blob/f7a4dc2f2d212f720fd201bab87971e6c508703d/src/coldfront_plugin_cloud/utils.py#L127). I'm not sure of the intention...

If we're filtering for change requests that happen both before the current value-change and the PREVIOUS value-change, would the following [if](https://github.com/nerc-project/coldfront-plugin-cloud/blob/f7a4dc2f2d212f720fd201bab87971e6c508703d/src/coldfront_plugin_cloud/utils.py#L131-L136) clause always fail?

A smaller question I have is: Are we assuming that an allocation will not be denied and/or activated more than once in its lifetime? Meaning allocations will always have ONE continuous time period where it is active?

Aside from these, I understand the billing code, and will begin working on the solution once you answer my questions.

**Comment by QuanMPhm** [comment]
@knikolla @joachimweyl After reviewing the test cases, I believe that the code I mentioned above led to unintended behavior?

**Comment by knikolla** [comment]
> @knikolla I was reviewing the storage billing code, and was confused by this [line](https://github.com/nerc-project/coldfront-plugin-cloud/blob/f7a4dc2f2d212f720fd201bab87971e6c508703d/src/coldfront_plugin_cloud/utils.py#L127). I'm not sure of the intention...
> 
> If we're filtering for change requests that happen both before the current value-change and the PREVIOUS value-change, would the following [if](https://github.com/nerc-project/coldfront-plugin-cloud/blob/f7a4dc2f2d212f720fd201bab87971e6c508703d/src/coldfront_plugin_cloud/utils.py#L131-L136) clause always fail?
> 
> A smaller question I have is: Are we assuming that an allocation will not be denied and/or activated more than once in its lifetime? Meaning allocations will always have ONE continuous time period where it is active?
> 
> Aside from these, I understand the billing code, and will begin working on the solution once you answer my questions.

@QuanMPhm I couldn't remember why either. You can look at the `git blame` of a particular line to find the corresponding commit that introduced it.

In this case https://github.com/nerc-project/coldfront-plugin-cloud/commit/f5382fbed76c742bbe900946f787588627414ba0

Does that help you?

**Comment by joachimweyl** [comment]
> @knikolla @joachimweyl After reviewing the test cases, I believe that the code I mentioned above led to unintended billing behavior?

@QuanMPhm thank you for the heads up. Do you have a clear path to resolve the issue?

**Comment by QuanMPhm** [comment]
I'll submit a PR that surfaces this bug, and we can consider next steps once we can confirm the bug and its potential impact.
