### ISSUE TITLE
[ColdFront/OpenShift] Implement integration testing

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#46]
Implement ColdFront integration testing

**Comment by joachimweyl** [comment]
@knikolla I added a label of size/medium to these 3 Issues outside of CCI-MOC. Please update them if this feels like the wrong size for any of these issues.

**Comment by joachimweyl** [comment]
@knikolla is this in [PR33](https://github.com/nerc-project/coldfront-plugin-openstack/pull/33)
