### ISSUE TITLE
Describe and create workflow for reapproval of EULA, on EULA update

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#77]
Currently, the screen to request EULA approval is only displayed when a PI requests a resource allocation.

We need to define our requirements and workflow for what happens when that EULA is updated post-PI approval.

ColdFront is accessed by PI's and will house only the EULA acceptance. RegApp will be accessed by all users when they sign up and therefore will display the GDPR (currently also including a section of the EULA).

- [x] Confirm email to PI's is enough with legal
- [ ] use code to gather list of emails to send updated EULA to

**Comment by joachimweyl** [comment]
currently, we display EULA from Github, and request the user to agree, we also track what version the EULA is currently on Github
next we need to:
1. save information about who accepted what version when
   1. this should be something we can go check and look at in some format
1. compare logins against the list and if somebody is not up to date make them accept the new version
   1. and/or email them to let them know the EULA updated and provide a link to the new EULA letting them know that if they don't agree with the new EULA they can close their account (not done)

**Comment by knikolla** [comment]
@joachimweyl 

It is important to clarify that the EULA is accepted "by a PI for a resource allocation." So when the EULA for a service changes, do we prompt 1-by-1 for each resource allocation? once for each project? once for each PI?

It is also important to define the distinction between what goes in RegApp (to be approved by all users, potentially gating loging to approval) and ColdFront.

**Comment by joachimweyl** [comment]
This is another good reason to go with option 2.i. from above that way we do not need to prompt at all other than sending them an email to let them know that the EULA has been updated and they can decide based on that update if they wish to maintain their service or remove their account.

**Comment by knikolla** [comment]
So sounds like all that is needed is something to generate a list of all active resource allocations for a service and make a list of their PIs. Which by itself sounds like something useful even outside of the EULA question.

**Comment by joachimweyl** [comment]
@knikolla & @naved001 yes that is correct we have updated the wording of the EULA and confirmed with legal that this approach is acceptable.
Now we need to create a way to:
1. Gather list of emails of active users who have accepted the EULA
1. Send an automated email to this list letting them know that the EULA has been updated and that their continued use of the project constitutes their acceptance of the new EULA.
   1. we should either include a link to the EULA
   1. or the text of the new EULA
   1. or both

**Comment by joachimweyl** [comment]
@naved001 I noticed this did not make it into the current sprint. Is this by design or did it fall through the cracks.

**Comment by naved001** [comment]
@joachimweyl I think we removed it from the sprint when planning. The idea was to add it back if I had more time in hand, and it looks like I may have enough to time to start working on this.

**Comment by joachimweyl** [comment]
@knikolla what are the next steps for this issue?

**Comment by knikolla** [comment]
#89 will provide a way to list all users/PIs for a Resource (or in general). That list can be used to send emails when the EULA updates. 

An email already went out to all users in RegApp to approve EULA on the RegApp side. Given that we don't have a separate EULA on the ColdFront side, I'm moving this issue back to backlog and will pick it back up after #89 is completed.

**Comment by joachimweyl** [comment]
@knikolla with #89 done what are the last steps for this issue?

**Comment by knikolla** [comment]
There is already a Runbook to get all users and their emails https://github.com/nerc-project/nerc-runbooks/blob/main/docs/how-to-get-latest-registered-users.md
