### ISSUE TITLE
The `validate_allocations` command should sync users

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-cloud#81]
Currently it only deals with quota, it should also sync users.

**Comment by naved001** [comment]
@knikolla looking for some guidance on this. 

This is what I will ultimately do to sync users once the method to get users in allocators is implemented (something like `allocator.get_users(project_id)`)

https://github.com/naved001/coldfront-plugin-cloud/commit/cd17c354bcb5038391b4d301e1ab7aaed7716925
