### ISSUE TITLE
Create HTTP endpoint to read current projects, PI, resource allocations, and users

### ISSUE THREAD

**Issue by Milstein** [nerc-project/coldfront-plugin-cloud#89]
To map the usage data in XdMod with who to bill for it, we need to provide a way for ColdFront to export the relationship between the following resources

- Projects
- Resource Allocations
- PI
- Users in Project

----------
Edited Original description
- Allow admin to export the current projects in excel and csv format from admin dashboard.
- To show graphs of all current projects on the Center Summary screen

**Comment by knikolla** [comment]
Updated the title after today's meeting discussion.

**Comment by knikolla** [comment]
There's already existing work on exposing users via an API in ColdFront that is being tracked at https://github.com/ubccr/coldfront/pull/425

I can use that as a starting point.

**Comment by rob-baron** [comment]
Do we have a idea of the actual format that you will be using to transfer the data?

**Comment by joachimweyl** [comment]
@knikolla Scott/Wayne has provided the Science/Domain list to be used for Coldfront and XDMoD:
Life Science, Physical Science, Statistics/Math, Social Science, Arts/Humanities, Business/Management, Computer Science/Engineering, Public Health/BioMedical, Other
please work with @Milstein can help map the current ColdFront values to these values.

**Comment by rob-baron** [comment]
Here is the data structure I am planning to construct from the data that you are planning to send:

{
        "HU": {
            "Name":"Harvard University",
            "Field":{
                "PS": {
                    "name":"Pysical Science",
                    "PIs": {
                        "rob@somecollege.edu" : {
                            "name": "Rob"
                            "Projects": {
                                "project1": {
                                    "name": "project 1"
                                },
                                "project2": {
                                    "name": "project 2"
                                }
                            }
                        }
                    }
                },
                "CS": {
                    "name":"Computer Science",
                    "Kristi@somecollege.edu": {}
                }
            }
        },
        "BU": {
            "Name":"Boston University",
            "Field":{
                "PS": {
                    "name":"Pysical Science",
                    "PIs": {
                        "Peter@somecollege.edu" : {}
                    }
                },
                "CS": {
                    "name":"Computer Science",
                    "PIs": {
                        "i": {}
                    }
                }
            }
        }
    }
    
    You are welcome to flatten this to something like the following which would be more general:
    
[  {
    "parent_id": Null,
    "level": NULL,
    "id": "HU",
    "name": "Harvard University"
    },
    {
    "parent": "HU",
    "level": "Field",
    "id": "PS-HU",
    "name": "Physical Science"
    },
    ...
]

This way the structure of the data coming from cold front is in long format and the specific parts of what xdmod needs is handled by configuration as opposed to building it in to the specification.

**Comment by rob-baron** [comment]
A few questions:

1) does cold-front or reg-app ever delete any information.

2) does cold-front have simple ids that can be used to identify users.  For example I need a unique ID for the combination of (institution, field-of-science, PI).  I would prefer that it is more compact than spelling out the entire name that way I don't have to worry with the field lengths that have to exist in xdmod (I haven't had to look them up yet).

3) Will the http endpoint output only current data, id, are you expecting xdmod to keep track of historical data or will cold-front and reg-app keep track of the historical data.

**Comment by joachimweyl** [comment]
@Milstein & @knikolla ^

**Comment by joachimweyl** [comment]
@knikolla what is the status of this issue?

**Comment by joachimweyl** [comment]
@knikolla when you get back please make wrapping this up your priority.

**Comment by knikolla** [comment]
Implementation is done at https://github.com/cci-moc/coldfront-plugin-api
