### ISSUE TITLE
Use published openshift-acct-mgt image rather than building our own

### ISSUE THREAD

**Issue by larsks** [nerc-project/coldfront-plugin-cloud#91]
In [`ci/microshift.py`][1] we are cloning the `openshift-acct-mgt` repository and building an image locally. Since that repository has had an image building workflow since cci-moc/openshift-acct-mgt#69, we should should use the appropriate tagged image.

[1]: https://github.com/nerc-project/coldfront-plugin-cloud/blob/caa0c5448f4eab6d59a0669ca4ac5d631eff5f5d/ci/microshift.sh#L38

**Comment by jtriley** [comment]
closed by #133
